language: node_js
node_js:
  - "0.12"
  - "4.1"
  - "4.2"

install:
  - npm install && cd node_modules/@cycle/dom && npm run compile-lib && cd ../../.. && cd node_modules/@cycle/isolate && npm run compile-lib && cd ../../..
